image: ruby:2.3

services:
  - postgres

variables:
  POSTGRES_DB: vapor_test
  POSTGRES_USER: vapor
  POSTGRES_PASSWORD: ""

cache:
  paths:
  - vendor/

test:
  script:
  - apt-get update -qy
  - apt-get install -y nodejs
  - cp config/database.yml.gitlab-ci config/database.yml
  - bundle install --path vendor
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rspec

development:
  type: deploy
  script:
  - mkdir /root/.ssh
  - echo $DEV_HOST_KEY > ~/.ssh/known_hosts
  - echo $DEV_KEY > ~/.ssh/id_rsa
  - chmod  400 ~/.ssh/id_rsa
  - git remote add dev $DEV_GIT_REPO
  - git push dev HEAD:master
  only:
  - master
