image: ruby:2.3.1

services:
  - postgres

variables:
  POSTGRES_DB: vapor_test
  POSTGRES_USER: vapor
  POSTGRES_PASSWORD: ""

cache:
  paths:
  - vendor/

test:
  script:
  - apt-get update -qy
  - apt-get install -y nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - mkdir ~/tmp
  - pushd ~/tmp
  - wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar xf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - mv phantomjs-2.1.1-linux-x86_64 phantomjs
  - ln -s ~/tmp/phantomjs/bin/phantomjs /usr/bin/phantomjs
  - phantomjs --version
  - popd
  - bundle install --path vendor --jobs $(nproc)  "${FLAGS[@]}"
  - cp config/database.yml.gitlab-ci config/database.yml
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec

development:
  type: deploy
  script:
  - mkdir /root/.ssh
  - echo $DEV_HOST_KEY > ~/.ssh/known_hosts
  - echo -e $DEV_KEY > ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa
  - git push $DEV_GIT_REPO HEAD:master
  only:
  - master

production:
  type: deploy
  script:
  - mkdir /root/.ssh
  - echo $PROD_HOST_KEY > ~/.ssh/known_hosts
  - echo -e $PROD_KEY > ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa
  - git push $PROD_GIT_REPO HEAD:master
  only:
  - tags

rubocop:
  script:
    - ruby -v
    - gem install bundler --no-ri --no-rdoc
    - bundle install --path vendor --jobs $(nproc)  "${FLAGS[@]}"
    - bundle exec rubocop
