Rails:
  Enabled: true

Documentation:
  Enabled: false

Style/SignalException:
  Exclude:
    - 'lib/devise/strategies/*.rb'

AllCops:
  Exclude:
    - 'bin/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "**/factories/**"
    - "**/tasks/**"

Style/DotPosition:
  Description: Checks the position of the dot in multi-line method calls.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-multi-line-chains
  Enabled: true
  EnforcedStyle: trailing
  SupportedStyles:
  - leading
  - trailing

Style/GuardClause:
  Enabled: false
