Rails:
  Enabled: true

Documentation:
  Enabled: false

Style/SignalException:
  Exclude:
    - 'lib/devise/strategies/*.rb'

AllCops:
  Exclude:
    - 'bin/*'
    - 'bin/**/*'

Metrics/LineLength:
  Max: 100
