defaults: &defaults
  jwt:
    key: <%= Rails.root.join('config', 'jwt', 'dev.pem') %>
    key_algorithm: ES256
    expiration_time: 3600
    issuer: 'EurValve Portal'


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  jwt_key: <%= Rails.root.join('config', 'jwt', 'prod.pem') %>
