defaults: &defaults
  jwt:
    key: <%= ENV['JWT_KEY_PATH'] || Rails.root.join('config', 'jwt', 'dev.pem') %>
    key_algorithm: ES256
    expiration_time: 86400 #24 hours
    issuer: 'IEE'
  redis_url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379' %>
  cloud:
    atmosphere_url: <%= ENV['ATMOSPHERE_BASE_URL'] || 'https://vph.cyfronet.pl' %>
    cloud_facade_path: '/api/v1/'
  clock:
    update: <%= ENV['CLOCK_UPDATE'] || 30 %> #seconds
  ansys:
    servers: <%= ENV['ANSYSLI_SERVERS'] %>
    license_file: <%= ENV['ANSYSLMD_LICENSE_FILE'] %>

development:
  <<: *defaults

test:
  <<: *defaults
  ansys:
    servers: ansys-servers
    license_file: ansys-license-file

production:
  <<: *defaults
  jwt:
    key: <%= Rails.root.join('config', 'jwt', 'prod.pem') %>
    key_algorithm: ES256
    expiration_time: 3600
    issuer: 'IEE'
