defaults: &defaults
  jwt:
    key: <%= ENV['JWT_KEY_PATH'] || Rails.root.join('config', 'jwt', 'dev.pem') %>
    key_algorithm: ES256
    expiration_time: 21600 #6 hours
    issuer: 'EurValve Portal'
  redis_url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379' %>
  file_store:
    web_dav_base_url: <%= ENV['WEB_DAV_BASE_URL'] || 'https://files.valve.cyfronet.pl' %>
    web_dav_base_path: '/webdav'
    web_dav_policy_proxy_path: '/portal-proxy'
  cloud:
    atmosphere_url: <%= ENV['ATMOSPHERE_BASE_URL'] || 'https://vph.cyfronet.pl' %>
    cloud_facade_path: '/api/v1/'
    computation_appliance_type: <%= ENV['ATMOSPHERE_APPLIANCE_TYPE'] || 886 %>
    computation_config_template: <%= ENV['ATMOSPHERE_CONFIG_TEMPLATE'] || 1388 %>
  data_sets:
    url: <%= ENV['DATA_SETS_BASE_URL'] || 'https://eurvalve.sheffield.ac.uk' %>
    site_path: <%= ENV['DATA_SETS_SITE_PATH'] || '/WebQuery/site.html' %>
    api_doc_path: '/eurvalve/WebQuery/api.png'
    api_url_path: '/WebQuery/api/JsonQuery/'
  clock:
    update: <%= ENV['CLOCK_UPDATE'] || 30 %> #seconds
  gitlab:
    host: <%= ENV['GITLAB_HOST'] || 'gitlab.com' %>
    clone_url: <%= "git@#{ENV['GITLAB_HOST'] || 'gitlab.com'}" %>
  ansys:
    servers: <%= ENV['ANSYSLI_SERVERS'] %>
    license_file: <%= ENV['ANSYSLMD_LICENSE_FILE'] %>

development:
  <<: *defaults

test:
  <<: *defaults
  gitlab:
    host: <%= ENV['GITLAB_HOST'] || 'gitlab.com' %>
    clone_url: git@gitlab-test.com
  ansys:
    servers: ansys-servers
    license_file: ansys-license-file

production:
  <<: *defaults
  jwt:
    key: <%= Rails.root.join('config', 'jwt', 'prod.pem') %>
    key_algorithm: ES256
    expiration_time: 3600
    issuer: 'EurValve Portal'
