defaults: &defaults
  jwt:
    key: <%= Rails.root.join('config', 'jwt', 'dev.pem') %>
    key_algorithm: ES256
    expiration_time: 3600
    issuer: 'EurValve Portal'
  redis_url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379' %>
  file_store:
    web_dav_base_url: "https://files.valve.cyfronet.pl/webdav"
    web_dav_base_href: "/webdav"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  jwt:
    key: <%= Rails.root.join('config', 'jwt', 'prod.pem') %>
    key_algorithm: ES256
    expiration_time: 3600
    issuer: 'EurValve Portal'

