defaults: &defaults
  jwt:
    key: <%= Rails.root.join('config', 'jwt', 'dev.pem') %>
    key_algorithm: ES256
    expiration_time: 3600
    issuer: 'EurValve Portal'
  redis_url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379' %>
  file_store:
    web_dav_base_url: <%= ENV['WEB_DAV_BASE_URL'] || 'https://files.valve.cyfronet.pl' %>
    web_dav_base_path: '/webdav'
    web_dav_policy_proxy_path: '/portal-proxy'
  cloud:
    atmosphere_url: <%= ENV['ATMOSPHERE_BASE_URL'] || 'https://vph.cyfronet.pl' %>
    cloud_facade_path: '/api/v1/'

development:
  <<: *defaults
  jwt:
    key: <%= Rails.root.join('config', 'jwt', 'prod.pem') %>
    key_algorithm: ES256
    expiration_time: 3600
    issuer: 'EurValve Portal'

test:
  <<: *defaults
  jwt:
    key: <%= Rails.root.join('config', 'jwt', 'prod.pem') %>
    key_algorithm: ES256
    expiration_time: 3600
    issuer: 'EurValve Portal'

production:
  <<: *defaults
  jwt:
    key: <%= Rails.root.join('config', 'jwt', 'prod.pem') %>
    key_algorithm: ES256
    expiration_time: 3600
    issuer: 'EurValve Portal'
