defaults: &defaults
  jwt:
    key: <%= ENV['JWT_KEY_PATH'] || Rails.root.join('config', 'jwt', 'dev.pem') %>
    key_algorithm: ES256
    expiration_time: 21600 #6 hours
    issuer: 'EurValve Portal'
  redis_url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379' %>
  file_store:
    web_dav_base_url: <%= ENV['WEB_DAV_BASE_URL'] || 'https://files.valve.cyfronet.pl' %>
    web_dav_base_path: '/webdav'
    web_dav_policy_proxy_path: '/portal-proxy'
  cloud:
    atmosphere_url: <%= ENV['ATMOSPHERE_BASE_URL'] || 'https://vph.cyfronet.pl' %>
    cloud_facade_path: '/api/v1/'
  data_sets:
    url: <%= ENV['DATA_SETS_BASE_URL'] || 'https://eurvalve.shef.ac.uk/eurvalve/WebQuery' %>
    site_path: '/site.html?dataset=eurvalve&host=eurvalve.shef.ac.uk'
    api_doc_path: '/api.png'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  jwt:
    key: <%= Rails.root.join('config', 'jwt', 'prod.pem') %>
    key_algorithm: ES256
    expiration_time: 3600
    issuer: 'EurValve Portal'
