redis: &redis
  adapter: redis
  url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379' %>

production:
  <<: *redis
  channel_prefix: vapor_production

development:
  <<: *redis
  channel_prefix: vapor_development

test:
  adapter: async
