defaults: &defaults
  rimrock:
    url: https://submit.plgrid.pl
    host: prometheus.cyfronet.pl
    tag: vapor

development:
  <<: *defaults
  storage_url: https://data.plgrid.pl/list/prometheus/net/archive/groups/plggeurvalve/test/

test:
  <<: *defaults
  storage_url: https://data.plgrid.pl/list/prometheus/net/archive/groups/plggeurvalve/test/

production:
  <<: *defaults
  storage_url: https://data.plgrid.pl/list/prometheus/net/archive/groups/plggeurvalve/
