defaults: &defaults
  data_synchronizer: PlgridDataFileSynchronizer
  rimrock:
    url: https://submit.plgrid.pl
    host: prometheus.cyfronet.pl
    tag: vapor

development:
  <<: *defaults
  data_synchronizer: WebdavDataFileSynchronizer
  storage_url: https://data.plgrid.pl/list/prometheus/net/archive/groups/plggeurvalve/development/
  handle_url: https://data.plgrid.pl/files/prometheus/net/archive/groups/plggeurvalve/development/

test:
  <<: *defaults
  data_synchronizer: WebdavDataFileSynchronizer
  storage_url: https://data.plgrid.pl/list/prometheus/net/archive/groups/plggeurvalve/test/
  handle_url: https://data.plgrid.pl/files/prometheus/net/archive/groups/plggeurvalve/test/

production:
  <<: *defaults
  storage_url: https://data.plgrid.pl/list/prometheus/net/archive/groups/plggeurvalve/production/
  handle_url: https://data.plgrid.pl/files/prometheus/net/archive/groups/plggeurvalve/production/
