defaults: &defaults
  rimrock:
    url: https://submit.plgrid.pl
    host: prometheus.cyfronet.pl
    tag: vapor
  grant_id: <%= ENV['GRANT_ID'] || 'eurvalve3' %>
  git_download_key: <%= ENV['PIPELINE_SSH_KEY'] %>
  owncloud:
    inputs_path: input
    outputs_path: output
    url: <%= ENV['OWNCLOUD_URL'] %>
    user: <%= ENV['OWNCLOUD_USER'] %>
    password: <%= ENV['OWNCLOUD_PASSWORD'] %>



development:
  <<: *defaults

test:
  <<: *defaults
  git_download_key: <%= Rails.root.join('spec', 'support', 'data_files', 'ssh_key') %>

production:
  <<: *defaults
