defaults: &defaults
  rimrock:
    url: https://submit.plgrid.pl
    host: prometheus.cyfronet.pl
    tag: vapor
  grant_id: <%= ENV['GRANT_ID'] || 'eurvalve3' %>
  git_download_key: <%= ENV['PIPELINE_SSH_KEY'] %>
  owncloud:
    inputs_path: input
    outputs_path: output
    url: <%= ENV['OWNCLOUD_URL'] %>
    user: <%= ENV['OWNCLOUD_USER'] %>
    password: <%= ENV['OWNCLOUD_PASSWORD'] %>
  git_repos:
    blood_flow_simulation: <%= ENV['PIPELINE_R_BFS'] || 'eurvalve/blood-flow' %>
    heart_model_calculation: <%= ENV['PIPELINE_R_HMS'] || 'eurvalve/0dmodel' %>
    parameter_extraction: <%= ENV['PIPELINE_R_PE'] || 'eurvalve/parameter-extraction' %>
    cfd: <%= ENV['PIPELINE_R_CFD'] || 'eurvalve/cfd' %>
    rom: <%= ENV['PIPELINE_R_ROM'] || 'eurvalve/cfd' %>
    parameter_optimization: <%= ENV['PIPELINE_R_PO'] || 'eurvalve/0dmodel' %>
    uncertainty_analysis: <%= ENV['PIPELINE_R_U'] || 'eurvalve/0dmodel' %>
  segmentation:
    mode: <%= ENV['SEGMENTATION_MODE'] || 3 %>


development:
  <<: *defaults

test:
  <<: *defaults
  git_download_key: <%= Rails.root.join('spec', 'support', 'data_files', 'ssh_key') %>

production:
  <<: *defaults
