defaults: &defaults
  rimrock:
    url: https://submit.plgrid.pl
    host: prometheus.cyfronet.pl
    tag: vapor
  cloudify:
    url: https://147.213.76.124/api/v3.1
    user: admin
    password: zAv1Y0KXC0VZ
    blueprint: compute-blueprint-beta
    iee_deployment_name: iee_deployment
    app_workflow_name: execute_operation
  grant_id: plgprocess3
  gpu_grant_id: <%= ENV['GPU_GRANT_ID'] || 'process2gpu' %>
  git_download_key: <%= ENV['PIPELINE_SSH_KEY'] %>
  staging:
    infra_host: 'http://lobcder.process-project.eu'
    infra_port: '30000'
    infra_path: '/api/v1/infrastructure'
    infra_token_header: 'x-access-token'
    uc1_infra_token:  <%= ENV['UC1_INFRA_TOKEN'] %>
    uc2_infra_token:  <%= ENV['UC2_INFRA_TOKEN'] %>
    uc4_infra_token:  <%= ENV['UC4_INFRA_TOKEN'] %>
    uc5_infra_token:  <%= ENV['UC5_INFRA_TOKEN'] %>
    staging_secret: <%= ENV['STAGING_SECRET'] %>
    folders_path: '/api/v1/folders'
    list_path: '/api/v1/list'
    copy_path: '/api/v1/copy'
    move_path: '/api/v1/move'
    status_path: '/api/v1/status'
    mkdir_path: '/api/v1/mkdir'
    rm_path: '/api/v1/remove'

  rest:
    host: 'https://gar.mnm-team.org'
    port: '5000'
    job_submission_path: '/submit/'
    job_status_path: '/status/'
development:
  <<: *defaults

test:
  <<: *defaults
  git_download_key: <%= Rails.root.join('spec', 'support', 'data_files', 'ssh_key') %>

production:
  <<: *defaults
