defaults: &defaults
  rimrock:
    url: https://submit.plgrid.pl
    host: prometheus.cyfronet.pl
    tag: vapor
  grant_id: <%= ENV['GRANT_ID'] || 'process1' %>
  git_download_key: <%= ENV['PIPELINE_SSH_KEY'] %>
  staging_in:
    host: 'data01.process-project.eu'
    port: '30136'
    path: '/api/v1/copy'
    lobcder_api_access_token: <%= ENV['LOBCDER_API_ACCESS_TOKEN'] %>
    staging_secret: <%= ENV['STAGING_SECRET'] %>
  segmentation:
    inputs_path: segmentation/input
    outputs_path: segmentation/output
    status_path: status
    url: <%= ENV['SEGMENTATION_URL'] %>
    ui_url: <%= ENV['SEGMENTATION_UI_URL'] %>
    user: <%= ENV['SEGMENTATION_USER'] %>
    password: <%= ENV['SEGMENTATION_PASSWORD'] %>


development:
  <<: *defaults

test:
  <<: *defaults
  git_download_key: <%= Rails.root.join('spec', 'support', 'data_files', 'ssh_key') %>

production:
  <<: *defaults
